[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 0, y = 0 }
opacity = 0.5
blur = true

[font]
normal = { family = "ComicMono Nerd Font", style = "Regular" }
bold = { family = "ComicMono Nerd Font", style = "bold" }
italic = { family = "ComicMono Nerd Font", style = "italic" }
bold_italic = { family = "ComicMono Nerd Font", style = "bold italic" }
size = 12

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[cursor]
style = { shape = "Beam", blinking = "On" }

[terminal]
shell = { program = "/usr/bin/zsh", args = ["-i"] }

[colors.primary]
foreground = "#ffffff" # White
background = "#000000" # Black

[colors.normal]
black = "#000000"
red = "#ff3b30"
green = "#4cd964"
yellow = "#ffcc00"
blue = "#007aff"
magenta = "#ff2d55"
cyan = "#5ac8fa"
white = "#ffffff"

[colors.bright]
black = "#686868"
red = "#ff3b30"
green = "#4cd964"
yellow = "#ffcc00"
blue = "#007aff"
magenta = "#ff2d55"
cyan = "#5ac8fa"
white = "#ffffff"

[keyboard]
bindings = [
    # Copy (Cmd + C)
    { key = "C", mods = "Command", action = "Copy" },

    # Paste (Cmd + V)
    { key = "V", mods = "Command", action = "Paste" },

    # Find (Cmd + F)
    { key = "F", mods = "Command", action = "SearchForward" },

    # New Window (Cmd + N)
    { key = "N", mods = "Command", action = "CreateNewWindow" },

    # Decrease Font Size (Cmd + -)
    { key = "Minus", mods = "Command", action = "DecreaseFontSize" },

    # Increase Font Size (Cmd + =)
    { key = "Equals", mods = "Command", action = "IncreaseFontSize" },

    # Reset Font Size (Cmd + 0)
    { key = "Key0", mods = "Command", action = "ResetFontSize" },

    # Toggle Full Screen (Cmd + Enter)
    { key = "Return", mods = "Command", action = "ToggleSimpleFullscreen" },

    # Switch to Specific Tab (Cmd + 1 ~ Cmd + 9)
    { key = "Key1", mods = "Command", action = "SelectTab1" },
    { key = "Key2", mods = "Command", action = "SelectTab2" },
    { key = "Key3", mods = "Command", action = "SelectTab3" },
    { key = "Key4", mods = "Command", action = "SelectTab4" },
    { key = "Key5", mods = "Command", action = "SelectTab5" },
    { key = "Key6", mods = "Command", action = "SelectTab6" },
    { key = "Key7", mods = "Command", action = "SelectTab7" },
    { key = "Key8", mods = "Command", action = "SelectTab8" },
    { key = "Key9", mods = "Command", action = "SelectTab9" },

    # Hide Alacritty (Cmd + H)
    { key = "H", mods = "Command", action = "Hide" },

    # Hide Other Applications (Cmd + Option + H)
    { key = "H", mods = "Command|Option", action = "HideOtherApplications" },


    # newline with shift enter for claude code
    { key = "Return", mods = "Shift", chars = "\\x1b\r"},
]

